export const clientEnv = {
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
  NEXT_PUBLIC_DOWNLOAD_URL: process.env.NEXT_PUBLIC_DOWNLOAD_URL,
  NEXT_PUBLIC_AUTHORIZATION_TOKEN: process.env.NEXT_PUBLIC_AUTHORIZATION_TOKEN,
  NEXT_PUBLIC_SEJARAH_URL: process.env.NEXT_PUBLIC_SEJARAH_URL,
  NEXT_PUBLIC_ASSETS_URL: process.env.NEXT_PUBLIC_ASSETS_URL,
};
